excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://tinypressco.github.io
title: The Tinypress blog
email: love@tinypress.co
author: Tinypress
description: Tinypress allows you create and easily manage your blog on Github.<br /><br /><a href="https://tinypress.co/">Get started now.</a>
paginate: 5
google_analytics: 